package ruokajajuoma.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokajajuoma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.04 12:11:10 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JuomatietoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi38 */
  @Test
  public void testRekisteroi38() {    // Juomatieto: 38
    Juomatieto punaviini = new Juomatieto(); 
    assertEquals("From: Juomatieto line: 40", 0, punaviini.getIdNumero()); 
    punaviini.rekisteroi(); 
    punaviini.rekisteroi(); 
    Juomatieto valkoviini = new Juomatieto(); 
    valkoviini.rekisteroi(); 
    valkoviini.rekisteroi(); 
    valkoviini.rekisteroi(); 
    int n1 = punaviini.getIdNumero(); 
    int n2 = valkoviini.getIdNumero(); 
    assertEquals("From: Juomatieto line: 49", n2-1, n1); 
  } // Generated by ComTest END
}