package ruokajajuoma.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import ruokajajuoma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.04 12:11:10 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class JuomatTest {



  // Generated by ComTest BEGIN
  /** testPoista48 */
  @Test
  public void testPoista48() {    // Juomat: 48
    Juomat juomat = new Juomat(); 
    Juoma juoma21 = new Juoma(2,1); 
    Juoma juoma11 = new Juoma(1,1); 
    Juoma juoma22 = new Juoma(2,2); 
    Juoma juoma12 = new Juoma(1,2); 
    juomat.lisaa(juoma21); 
    juomat.lisaa(juoma11); 
    juomat.lisaa(juoma22); 
    juomat.lisaa(juoma12); 
    assertEquals("From: Juomat line: 58", false, juomat.poista(2,3)); 
    assertEquals("From: Juomat line: 59", 4, juomat.getLkm()); 
    assertEquals("From: Juomat line: 60", true, juomat.poista(1,1)); 
    assertEquals("From: Juomat line: 61", 3, juomat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaRuokaJuomilta84 */
  @Test
  public void testPoistaRuokaJuomilta84() {    // Juomat: 84
    Juomat juomat = new Juomat(); 
    Juoma juoma21 = new Juoma(2,1); 
    Juoma juoma11 = new Juoma(1,1); 
    Juoma juoma22 = new Juoma(2,2); 
    Juoma juoma12 = new Juoma(1,2); 
    juomat.lisaa(juoma21); 
    juomat.lisaa(juoma11); 
    juomat.lisaa(juoma22); 
    juomat.lisaa(juoma12); 
    assertEquals("From: Juomat line: 94", true, juomat.poistaRuokaJuomilta(2)); 
    assertEquals("From: Juomat line: 95", 2, juomat.getLkm()); 
    assertEquals("From: Juomat line: 96", true, juomat.poistaRuokaJuomilta(1)); 
    assertEquals("From: Juomat line: 97", 0, juomat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaJuomaRuoilta120 */
  @Test
  public void testPoistaJuomaRuoilta120() {    // Juomat: 120
    Juomat juomat = new Juomat(); 
    Juoma juoma21 = new Juoma(2,1); 
    Juoma juoma11 = new Juoma(1,1); 
    Juoma juoma22 = new Juoma(2,2); 
    Juoma juoma12 = new Juoma(1,2); 
    juomat.lisaa(juoma21); 
    juomat.lisaa(juoma11); 
    juomat.lisaa(juoma22); 
    juomat.lisaa(juoma12); 
    assertEquals("From: Juomat line: 130", true, juomat.poistaRuokaJuomilta(2)); 
    assertEquals("From: Juomat line: 131", 2, juomat.getLkm()); 
    assertEquals("From: Juomat line: 132", true, juomat.poistaRuokaJuomilta(1)); 
    assertEquals("From: Juomat line: 133", 0, juomat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta180 */
  @Test
  public void testLueTiedostosta180() {    // Juomat: 180
    Juomat juomat = new Juomat(); 
    Juoma juoma1 = new Juoma(1,1), juoma2 = new Juoma(2,3); 
    String hakemisto = "testilinkit"; 
    String tiedNimi = hakemisto+"/nimet"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    juomat.lueTiedostosta(tiedNimi); 
    juomat.lisaa(juoma1); 
    juomat.lisaa(juoma2); 
    juomat.tallenna(); 
    juomat = new Juomat();  // Poistetaan vanhat luomalla uusi
    juomat.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    assertEquals("From: Juomat line: 197", juoma1.toString(), juomat.anna(0).toString()); 
    assertEquals("From: Juomat line: 198", juoma2.toString(), juomat.anna(1).toString()); 
    assertEquals("From: Juomat line: 199", 2, juomat.getLkm()); 
    juomat.lisaa(juoma2); 
    juomat.tallenna(); 
    assertEquals("From: Juomat line: 203", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Juomat line: 205", true, fbak.delete()); 
    assertEquals("From: Juomat line: 206", true, dir.delete()); 
  } // Generated by ComTest END
}