package ruokajajuoma.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import ruokajajuoma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.04 12:11:10 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class OstopaikatTest {



  // Generated by ComTest BEGIN
  /** testLisaa34 */
  @Test
  public void testLisaa34() {    // Ostopaikat: 34
    Ostopaikat ostopaikat  = new Ostopaikat(); 
    Ostopaikkatieto kauppaCM = new Ostopaikkatieto(), kauppaSM = new Ostopaikkatieto(); 
    assertEquals("From: Ostopaikat line: 37", 0, ostopaikat.getLkm()); 
    ostopaikat.lisaa(kauppaCM); assertEquals("From: Ostopaikat line: 38", 1, ostopaikat.getLkm()); 
    ostopaikat.lisaa(kauppaSM); assertEquals("From: Ostopaikat line: 39", 2, ostopaikat.getLkm()); 
    ostopaikat.lisaa(kauppaCM); assertEquals("From: Ostopaikat line: 40", 3, ostopaikat.getLkm()); 
    assertEquals("From: Ostopaikat line: 41", kauppaCM, ostopaikat.anna(0)); 
    assertEquals("From: Ostopaikat line: 42", kauppaSM, ostopaikat.anna(1)); 
    assertEquals("From: Ostopaikat line: 43", kauppaCM, ostopaikat.anna(2)); 
    assertEquals("From: Ostopaikat line: 44", false, ostopaikat.anna(1) == kauppaCM); 
    assertEquals("From: Ostopaikat line: 45", true, ostopaikat.anna(1) == kauppaSM); 
    ostopaikat.lisaa(kauppaCM); assertEquals("From: Ostopaikat line: 46", 4, ostopaikat.getLkm()); 
    ostopaikat.lisaa(kauppaCM); assertEquals("From: Ostopaikat line: 47", 5, ostopaikat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista61 */
  @Test
  public void testPoista61() {    // Ostopaikat: 61
    Ostopaikat ostopaikat = new Ostopaikat(); 
    Ostopaikkatieto paikka21 = new Ostopaikkatieto(); paikka21.rekisteroi(); 
    Ostopaikkatieto paikka11 = new Ostopaikkatieto(); paikka11.rekisteroi(); 
    Ostopaikkatieto paikka22 = new Ostopaikkatieto(); paikka22.rekisteroi(); 
    Ostopaikkatieto paikka12 = new Ostopaikkatieto(); paikka12.rekisteroi(); 
    Ostopaikkatieto paikka23 = new Ostopaikkatieto(); paikka23.rekisteroi(); 
    ostopaikat.lisaa(paikka21); 
    ostopaikat.lisaa(paikka11); 
    ostopaikat.lisaa(paikka22); 
    ostopaikat.lisaa(paikka12); 
    assertEquals("From: Ostopaikat line: 72", false, ostopaikat.poista(paikka23.getIdNumero())); 
    assertEquals("From: Ostopaikat line: 73", 4, ostopaikat.getLkm()); 
    assertEquals("From: Ostopaikat line: 74", true, ostopaikat.poista(paikka11.getIdNumero())); 
    assertEquals("From: Ostopaikat line: 75", 3, ostopaikat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLueTiedostosta121 */
  @Test
  public void testLueTiedostosta121() {    // Ostopaikat: 121
    Ostopaikat ostopaikat = new Ostopaikat(); 
    Ostopaikkatieto ostopaikkatieto1 = new Ostopaikkatieto(), ostopaikkatieto2 = new Ostopaikkatieto(); 
    ostopaikkatieto1.taytaPaikka(); 
    ostopaikkatieto2.taytaPaikka(); 
    String hakemisto = "testipaikat"; 
    String tiedNimi = hakemisto+"/nimet"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    ostopaikat.lueTiedostosta(tiedNimi); 
    ostopaikat.lisaa(ostopaikkatieto1); 
    ostopaikat.lisaa(ostopaikkatieto2); 
    ostopaikat.tallenna(); 
    ostopaikat = new Ostopaikat();  // Poistetaan vanhat luomalla uusi
    ostopaikat.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    assertEquals("From: Ostopaikat line: 140", ostopaikkatieto1.toString(), ostopaikat.anna(0).toString()); 
    assertEquals("From: Ostopaikat line: 141", ostopaikkatieto2.toString(), ostopaikat.anna(1).toString()); 
    assertEquals("From: Ostopaikat line: 142", 2, ostopaikat.getLkm()); 
    ostopaikat.lisaa(ostopaikkatieto2); 
    ostopaikat.tallenna(); 
    assertEquals("From: Ostopaikat line: 146", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Ostopaikat line: 148", true, fbak.delete()); 
    assertEquals("From: Ostopaikat line: 149", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTietoId235 */
  @Test
  public void testAnnaTietoId235() {    // Ostopaikat: 235
    Ostopaikat ostopaikat = new Ostopaikat(); 
    Ostopaikkatieto ostopaikkatieto1 = new Ostopaikkatieto(), ostopaikkatieto2 = new Ostopaikkatieto(), ostopaikkatieto3 = new Ostopaikkatieto(); 
    ostopaikkatieto1.rekisteroi(); ostopaikkatieto2.rekisteroi(); ostopaikkatieto3.rekisteroi(); 
    int id1 = ostopaikkatieto1.getIdNumero(); 
    ostopaikat.lisaa(ostopaikkatieto1); ostopaikat.lisaa(ostopaikkatieto2); ostopaikat.lisaa(ostopaikkatieto3); 
    assertEquals("From: Ostopaikat line: 241", true, ostopaikat.annaTietoId(id1  ) == ostopaikkatieto1); 
    assertEquals("From: Ostopaikat line: 242", true, ostopaikat.annaTietoId(id1+1) == ostopaikkatieto2); 
    assertEquals("From: Ostopaikat line: 243", true, ostopaikat.annaTietoId(id1+2) == ostopaikkatieto3); 
  } // Generated by ComTest END
}