package ruokajajuoma.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokajajuoma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.04 12:11:10 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RuokaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi32 */
  @Test
  public void testRekisteroi32() {    // Ruoka: 32
    Ruoka savukala = new Ruoka(); 
    assertEquals("From: Ruoka line: 34", 0, savukala.getIdNumero()); 
    savukala.rekisteroi(); 
    savukala.rekisteroi(); 
    Ruoka lakritsikala = new Ruoka(); 
    lakritsikala.rekisteroi(); 
    lakritsikala.rekisteroi(); 
    lakritsikala.rekisteroi(); 
    int n1 = savukala.getIdNumero(); 
    int n2 = lakritsikala.getIdNumero(); 
    assertEquals("From: Ruoka line: 43", n2-1, n1); 
  } // Generated by ComTest END
}