package ruokajajuoma.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import ruokajajuoma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.07 22:30:34 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RuokajuomaTest {


  // Generated by ComTest BEGIN  // Ruokajuoma: 30
   private Ruokajuoma ruokajuoma; 
   private Ruoka ruoka1; 
   private Ruoka ruoka2; 
   private int rid1; 
   private int rid2; 
   private Juomatieto jt21; 
   private Juomatieto jt11; 
   private Juomatieto jt22; 
   private Juomatieto jt12; 
   private Juomatieto jt23; 
   private Juoma jp1; 
   private Juoma jp2; 
   private Juoma jp3; 
   private Ostopaikkatieto op1; 
   private Ostopaikkatieto op2; 

   public void alustaTestiin() {
     ruokajuoma = new Ruokajuoma(); 
     ruoka1 = new Ruoka(); ruoka1.taytaKala(); ruoka1.rekisteroi(); 
     ruoka2 = new Ruoka(); ruoka2.taytaKala(); ruoka2.rekisteroi(); 
     rid1 = ruoka1.getIdNumero(); 
     rid2 = ruoka2.getIdNumero(); 
     jt21 = new Juomatieto(); jt21.rekisteroi(); jt21.taytaViini(); 
     jt11 = new Juomatieto(); jt11.rekisteroi(); jt11.taytaViini(); 
     jt22 = new Juomatieto(); jt22.rekisteroi(); jt22.taytaViini(); 
     jt12 = new Juomatieto(); jt12.rekisteroi(); jt12.taytaViini(); 
     jt23 = new Juomatieto(); jt23.rekisteroi(); jt23.taytaViini(); 
     ruokajuoma.lisaa(ruoka1); 
     ruokajuoma.lisaa(ruoka2); 
     ruokajuoma.lisaa(jt21); 
     ruokajuoma.lisaa(jt11); 
     ruokajuoma.lisaa(jt22); 
     ruokajuoma.lisaa(jt12); 
     ruokajuoma.lisaa(jt23); 
     jp1 = new Juoma(ruoka1.getIdNumero(), jt12.getIdNumero()); 
     jp2 = new Juoma(ruoka1.getIdNumero(), jt11.getIdNumero()); 
     jp3 = new Juoma(ruoka2.getIdNumero(), jt21.getIdNumero()); 
     ruokajuoma.lisaa(jp1); 
     ruokajuoma.lisaa(jp2); 
     ruokajuoma.lisaa(jp3); 
     op1 = new Ostopaikkatieto(); op1.taytaPaikka(); op1.rekisteroi(); 
     op2 = new Ostopaikkatieto(); op2.taytaPaikka(); op2.rekisteroi(); 
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaJuomatRuoalle189 */
  @Test
  public void testAnnaJuomatRuoalle189() {    // Ruokajuoma: 189
    alustaTestiin(); 
    Ruoka ruoka3 = new Ruoka(); 
    ruoka3.rekisteroi(); 
    ruokajuoma.lisaa(ruoka3); 
    ArrayList<Juomatieto> loytyneet; 
    loytyneet = ruokajuoma.annaJuomatRuoalle(ruoka3); 
    assertEquals("From: Ruokajuoma line: 198", 0, loytyneet.size()); 
    loytyneet = ruokajuoma.annaJuomatRuoalle(ruoka1); 
    assertEquals("From: Ruokajuoma line: 200", 2, loytyneet.size()); 
    assertEquals("From: Ruokajuoma line: 201", true, loytyneet.get(0) == jt12); 
    assertEquals("From: Ruokajuoma line: 202", true, loytyneet.get(1) == jt11); 
    loytyneet = ruokajuoma.annaJuomatRuoalle(ruoka2); 
    assertEquals("From: Ruokajuoma line: 204", 1, loytyneet.size()); 
    assertEquals("From: Ruokajuoma line: 205", true, loytyneet.get(0) == jt21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa298 */
  @Test
  public void testLisaa298() {    // Ruokajuoma: 298
    Ruoat ruoat = new Ruoat(); 
    Ruoka savukala = new Ruoka(), lakritsikala = new Ruoka(); 
    assertEquals("From: Ruokajuoma line: 302", 0, ruoat.getLkm()); 
    ruoat.lisaa(savukala); assertEquals("From: Ruokajuoma line: 303", 1, ruoat.getLkm()); 
    ruoat.lisaa(lakritsikala); assertEquals("From: Ruokajuoma line: 304", 2, ruoat.getLkm()); 
    ruoat.lisaa(savukala); assertEquals("From: Ruokajuoma line: 305", 3, ruoat.getLkm()); 
    assertEquals("From: Ruokajuoma line: 306", savukala, ruoat.anna(0)); 
    assertEquals("From: Ruokajuoma line: 307", lakritsikala, ruoat.anna(1)); 
    assertEquals("From: Ruokajuoma line: 308", savukala, ruoat.anna(2)); 
    assertEquals("From: Ruokajuoma line: 309", false, ruoat.anna(1) == savukala); 
    assertEquals("From: Ruokajuoma line: 310", true, ruoat.anna(1) == lakritsikala); 
    ruoat.lisaa(savukala); assertEquals("From: Ruokajuoma line: 312", 4, ruoat.getLkm()); 
    ruoat.lisaa(savukala); assertEquals("From: Ruokajuoma line: 313", 5, ruoat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKorvaaTaiLisaa349 */
  @Test
  public void testKorvaaTaiLisaa349() {    // Ruokajuoma: 349
    alustaTestiin(); 
    assertEquals("From: Ruokajuoma line: 351", 2, ruokajuoma.etsi("*",0).size()); 
    ruokajuoma.korvaaTaiLisaa(ruoka1); 
    assertEquals("From: Ruokajuoma line: 353", 2, ruokajuoma.etsi("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista414 
   * @throws Exception when error
   */
  @Test
  public void testPoista414() throws Exception {    // Ruokajuoma: 414
    alustaTestiin(); 
    assertEquals("From: Ruokajuoma line: 417", 2, ruokajuoma.etsi("*",0).size()); 
    assertEquals("From: Ruokajuoma line: 418", 1, ruokajuoma.annaRuoatJuomalle(jt11).size()); 
    assertEquals("From: Ruokajuoma line: 419", 1, ruokajuoma.poista(ruoka1)); 
    assertEquals("From: Ruokajuoma line: 420", 1, ruokajuoma.etsi("*",0).size()); 
    assertEquals("From: Ruokajuoma line: 421", 0, ruokajuoma.annaRuoatJuomalle(jt11).size()); 
    assertEquals("From: Ruokajuoma line: 422", 1, ruokajuoma.annaRuoatJuomalle(jt21).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista438 
   * @throws Exception when error
   */
  @Test
  public void testPoista438() throws Exception {    // Ruokajuoma: 438
    alustaTestiin(); 
    assertEquals("From: Ruokajuoma line: 441", 2, ruokajuoma.etsi("*",0).size()); 
    assertEquals("From: Ruokajuoma line: 442", 2, ruokajuoma.annaJuomatRuoalle(ruoka1).size()); 
    int tark = jt11.getIdNumero(); 
    assertEquals("From: Ruokajuoma line: 444", tark, ruokajuoma.poista(jt11)); 
    assertEquals("From: Ruokajuoma line: 446", 2, ruokajuoma.etsi("*",0).size()); 
    assertEquals("From: Ruokajuoma line: 447", 1, ruokajuoma.annaJuomatRuoalle(ruoka1).size()); 
    assertEquals("From: Ruokajuoma line: 448", 1, ruokajuoma.annaJuomatRuoalle(ruoka2).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi481 */
  @Test
  public void testEtsi481() {    // Ruokajuoma: 481
    alustaTestiin(); 
    Ruoka ruoka3 = new Ruoka(); ruoka3.rekisteroi(); 
    ruoka3.setNimi("Kanakeitto"); 
    ruokajuoma.lisaa(ruoka3); 
    Collection<Ruoka> loytyneet = ruokajuoma.etsi("*keitto*",0); 
    assertEquals("From: Ruokajuoma line: 489", 1, loytyneet.size()); 
  } // Generated by ComTest END
}